### PR TITLE
Support for div()

### PR DESCRIPTION
**Pull request by ipapadop**

### CODE REVIEW

**Comment by godbyk** [comment]
Should `ldiv()`, `lldiv()`, and `imaxdiv()` be added as well?

**Comment by Morwenn** [comment]
Before giving comments about specific points, I actually wonder whether the function is relevant for this library: as far as I know, the primary purpose of `std::div` is to have a standard way to compute both `x/y` and `x%y` in a single instruction. While this is great to optimize runtime programs, I'm not sure that it is something that we really want for a compile-time math library.

The only advantage I see is that its result type works with structured bindings in C++17; which is nice, but I'm not sure whether it is enough of an advantage to include the function.

**Comment by ipapadop** [comment]
My specific use-case: I have some functions that use `std` math functions which I needed to use in a constexpr. It made sense for my use-case to change from `std::div` to `smath::div` (same with `abs` etc.) instead of changing every call to something equivalent.

If parity with `cmath` is not a target for this library, then I would agree with the comment about the function not being relevant. If parity is required, then I should probably provide the rest of the `div` functions.

**Comment by Morwenn** [comment]
Actually there was no target at first for that library, I'm not even anywhere near a math expert, the library just got some traction and contributions because there was no equivalent at the time ^^"

If you've got a valid use case and it actually helps you, it's fine with me. Now that the motivation part has been clarified, let's get to the technical comments:
* Is the `std::div_t` family the best thing for the return type? It restricts the possible parameters to built-in integer types while it would be easy to extend. A more generic solution would be to provide an `smath::div_t` class template which does the same thing, and if really needed we could make specializations for built-in integer types inherit from the standard library types. That way you would get everything to work with `auto` but also with declarations of the form `std::div_t res = smath::div(x, y);`. I don't know whether it's worse going that far but it should work conveniently.
* I don't want to add `ldiv`, `lldiv` and `imaxdiv`: the generic overloads are sufficient.
* If we use `std::div_t` & friends, we will need to include `<cstdlib>` as well as `<cstdint>` to get all the types. Your implementation currently has some compile-time errors on the continuous integration because of that.
* You used designated initializers to initialize the return type of `div`, but this won't work with `-Wpedantic` prior to C++20.

Once the small design question about the return type is resolved, we can get to fixing the smaller problems mentioned above :)

**Comment by ipapadop** [comment]
- It is convenient, as it is a literal type. The current implementation only works with integral types anyway. The trick is that `smath::div` can return `std::ldiv_t` and `std::lldiv_t` depending on the arguments. We can have a `smath::div_t` but it will have to have an implicit conversion to `std::div_t` and the rest of the family. So if we have a `smath::div_t` then I'll need to add the proper conversions (and include `cstdlib` and ` cinttypes`). I am not very opinionated either way.
- OK.
- Correct; gcc seems pretty happy, I should have tested with clang first.
- Yup.

**Comment by Morwenn** [comment]
I would propose an implementation along these lines if you're fine with it:

```cpp
template<typename T, typename Enable=void>
struct div_t
{
    T quot;
    T rem;
};

template<>
struct div_t<int, void>:
    std::div_t
{};

template<>
struct div_t<long, void>:
    std::ldiv_t
{};

template<>
struct div_t<long long, void>:
    std::lldiv_t
{};

template<typename T>
struct div_t<
    T,
    std::enable_if_t<
        std::is_same<T, std::intmax_t>::value && not std::is_same<T, long long>::value
    >
>:
    std::imaxdiv_t
{};

template<typename T>
constexpr div_t<T> div(T x, T y)
{
    return { x / y, x % y };
}
```

I checked it to make sure that it wouldn't cause a problem with overload resolution and turns out that it fails to compile only when `std::div` also fails to compile (*e.g.* when the parameters don't have the same type) and works even where `std::div` doesn't (*e.g.* unsigned integer types).

There was a subtlety with `std::intmax_t` because it can be an alias for `long long`, hence the SFINAE trickery to get around this. Now I'm wondering whether it could be sane to actually accept parameters of different types and return `div_t<std::common_type_t<T, U>>` but if the main purpose is to replace existing use of `std::div` I don't think it's worth the trouble.

**Comment by ipapadop** [comment]
Unfortunately I can't just derive from `std::div_t` and friends and expect that `quot` and `rem` are in that order in the struct (ISO C11 7.22.6.2) so in that case I will have to explicitly initialize each value.

How about this?
`
template<typename T>
struct div_t
{
    T quot;
    T rem;
};

template<typename T>
constexpr typename std::enable_if<std::is_integral<T>::value, div_t<T>>::type div(T x, T y)
{
    return { x / y, x % y };
}
`

Since we have to support it for `std::intmax_t` too, then I think it would make sense to let one of the specializations take care of it implicitly, as it is an alias to any of those.

**Comment by Morwenn** [comment]
Oh, good catch, it would make the implementation harder to get right without clever tricks and I'm indeed not willing to go that far (and as you say we don't need specific support for `std::intmax_t` that way, it will be handled by the generic case).

Let's go for the simple implementation then. I don't think that we need to restrict it to built-in integral types though: letting it fail for types that don't handle `operator/` os `operator%` should be enough, I wouldn't want to gratuitously make it fail for user-defined interal-like types :)

**Comment by ipapadop** [comment]
The only issue with our own `div_t<T>` is that there has to be an implicit conversions for `std:div_t`, `std::ldiv_t` etc. as appropriate, so that `std::div_t d = smath::div(...)` would work. Let me work a bit more on that but I am leaning towards having specializations as before and doing assignment as the latter approach.

**Comment by Morwenn** [comment]
Yeah, that's what I was proposing, sorry for not being clear: having the `smath::div_t` imlpemented with specializations so that it inherits from `std::divt_t` and friends when it needs to, and `smath::div` implemented with assignments. I tried it with online compilers and it seems to work smoothly enough.

You can modify the pull request if you want, otherwise I can commit the code tonight and add a few more tests for the conversions to the `std::div_t` family of types.

**Comment by Morwenn** [comment]
I've implemented `smath::div` as mentioned and added tests (which passed CI) and documentation, I think we're good. Thanks for the contribution and discussion :)

**Comment by ipapadop** [comment]
You beat me to it. OK, thanks :+1:

**Pull request closed without merging**
